const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("cineviral", {
  bootstrap: () => ipcRenderer.invoke("app:bootstrap"),
  productionQueueList: () => ipcRenderer.invoke('production:list'),
  productionQueueAdd: (ids) => ipcRenderer.invoke('production:add', ids),
  productionQueueAddVideos: (templateId) => ipcRenderer.invoke('production:addVideos', templateId),
  productionQueueAddUrls: (templateId, urls) => ipcRenderer.invoke('production:addUrls', templateId, urls),
  productionQueueAction: (id, action) => ipcRenderer.invoke('production:action', id, action),
  productionQueueOpen: (id) => ipcRenderer.invoke('production:open', id),
  onProductionProgress: (callback) => {
    ipcRenderer.removeAllListeners('production:progress');
    ipcRenderer.on('production:progress', (_event, payload) => callback(payload));
  },
  pickVideo: () => ipcRenderer.invoke("dialog:pickVideo"),
  pickAudio: () => ipcRenderer.invoke("dialog:pickAudio"),
  pickSubtitle: () => ipcRenderer.invoke("dialog:pickSubtitle"),
  pickJson: () => ipcRenderer.invoke("dialog:pickJson"),
  pickJsonFiles: () => ipcRenderer.invoke("dialog:pickJsonFiles"),
  pickFolder: () => ipcRenderer.invoke("dialog:pickFolder"),
  downloadSourceFromUrl: (payload) => ipcRenderer.invoke("source:downloadUrl", payload),
  openFile: (filePath) => ipcRenderer.invoke("file:open", filePath),
  probeVideo: (videoPath) => ipcRenderer.invoke("video:probe", videoPath),
  createMirrorFlipVideo: (payload) => ipcRenderer.invoke("video:mirrorFlip", payload),
  openMirrorOutput: (outputPath) => ipcRenderer.invoke("video:openOutputFile", outputPath),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (payload) => ipcRenderer.invoke("settings:save", payload),
  checkSettings: (payload) => ipcRenderer.invoke("settings:check", payload),
  testVertex: (payload) => ipcRenderer.invoke("vertex:test", payload),
  getVertexBudgetStatus: (payload) => ipcRenderer.invoke("vertex:budgetStatus", payload),
  listOllamaModels: () => ipcRenderer.invoke("ollama:listModels"),
  getOllamaModelInfo: (modelName) => ipcRenderer.invoke("ollama:modelInfo", modelName),
  prepareHyMt2: (modelName) => ipcRenderer.invoke("translation:prepareHyMt2", modelName),
  createManualGeminiPack: (payload) => ipcRenderer.invoke("analysis:createManualGeminiPack", payload),
  runManualAntigravityStage1: (payload) => ipcRenderer.invoke("analysis:runManualAntigravityStage1", payload),
  cancelManualAntigravityStage1: () => ipcRenderer.invoke("analysis:cancelManualAntigravityStage1"),
  runConfiguredAiStage1: (payload) => ipcRenderer.invoke("analysis:runConfiguredAiStage1", payload),
  cancelConfiguredAi: () => ipcRenderer.invoke("analysis:cancelConfiguredAi"),
  importManualGeminiEvidence: (payload) => ipcRenderer.invoke("analysis:importManualGeminiEvidence", payload),
  importPodcastCandidates: (payload) => ipcRenderer.invoke("analysis:importPodcastCandidates", payload),
  importManualGeminiBlueprint: (payload) => ipcRenderer.invoke("analysis:importManualGeminiBlueprint", payload),
  inspectGeminiJsonFiles: (filePaths) => ipcRenderer.invoke("analysis:inspectGeminiJsonFiles", filePaths),
  getHookCandidates: (packageDir) => ipcRenderer.invoke("analysis:getHookCandidates", packageDir),
  lockHookContract: (payload) => ipcRenderer.invoke("analysis:lockHookContract", payload),
  createProject: (payload) => ipcRenderer.invoke("project:create", payload),
  runAutoStoryPipeline: (projectId, options) => ipcRenderer.invoke("autoStory:run", projectId, options),
  cancelAutoStoryPipeline: () => ipcRenderer.invoke("autoStory:cancel"),
  listProjects: () => ipcRenderer.invoke("project:list"),
  getProject: (projectId) => ipcRenderer.invoke("project:get", projectId),
  planProject: (projectId) => ipcRenderer.invoke("project:plan", projectId),
  ingestDubbingProject: (projectId) => ipcRenderer.invoke("project:ingestDubbing", projectId),
  rewriteScriptProject: (projectId) => ipcRenderer.invoke("project:rewriteScript", projectId),
  importStorytimeProject: (projectId) => ipcRenderer.invoke("project:importStorytime", projectId),
  importHighlightCutProject: (projectId) => ipcRenderer.invoke("project:importHighlightCut", projectId),
  importReviewedScriptProject: (projectId, jsonPath) => ipcRenderer.invoke("project:importReviewedScript", projectId, jsonPath),
  createGeminiDraftReviewPackage: (projectId) => ipcRenderer.invoke("project:createGeminiDraftReviewPackage", projectId),
  runConfiguredAiDraftReview: (projectId, packageDir) => ipcRenderer.invoke("project:runConfiguredAiDraftReview", projectId, packageDir),
  getDraftReviewReport: (projectId, variantId) => ipcRenderer.invoke("project:getDraftReviewReport", projectId, variantId),
  getViralRepairContext: (projectId) => ipcRenderer.invoke("project:getViralRepairContext", projectId),
  translateDubbingProject: (projectId) => ipcRenderer.invoke("project:translateDubbing", projectId),
  diarizeDubbingProject: (projectId) => ipcRenderer.invoke("project:diarizeDubbing", projectId),
  updateDubbingSegments: (projectId, segments) => ipcRenderer.invoke("project:updateDubbingSegments", projectId, segments),
  updateProjectPlan: (projectId, analysis) => ipcRenderer.invoke("project:updatePlan", projectId, analysis),
  updateProjectSettings: (projectId, partial) => ipcRenderer.invoke("project:updateSettings", projectId, partial),
  reviewSceneScript: (projectId, segmentIndex) => ipcRenderer.invoke("project:reviewSceneScript", projectId, segmentIndex),
  rewriteFailedScenes: (projectId) => ipcRenderer.invoke("project:rewriteFailedScenes", projectId),
  previewProject: (projectId) => ipcRenderer.invoke("project:preview", projectId),
  renderProject: (projectId) => ipcRenderer.invoke("project:render", projectId),
  resumeRender: (projectId) => ipcRenderer.invoke("project:resumeRender", projectId),
  cancelRender: () => ipcRenderer.invoke("project:cancelRender"),
  renderHighlightVariants: (projectId) => ipcRenderer.invoke("project:renderHighlightVariants", projectId),
  renderHighlightDraftVariants: (projectId) => ipcRenderer.invoke("project:renderHighlightDraftVariants", projectId),
  buildAudioPlan: (projectId) => ipcRenderer.invoke("project:audioPlan", projectId),
  renderSegmentVoice: (projectId, segmentIndex) => ipcRenderer.invoke("project:renderSegmentVoice", projectId, segmentIndex),
  renderSegmentPreview: (projectId, segmentIndex) => ipcRenderer.invoke("project:renderSegmentPreview", projectId, segmentIndex),
  renderFastDraft: (projectId) => ipcRenderer.invoke("project:renderFastDraft", projectId),
  runRecap: (projectId, options) => ipcRenderer.invoke("recap:run", projectId, options),
  getRecapReviewState: (projectId) => ipcRenderer.invoke("recap:getReviewState", projectId),
  updateRecapReview: (projectId, payload) => ipcRenderer.invoke("recap:updateDecisions", projectId, payload),
  renderRecapFinal: (projectId) => ipcRenderer.invoke("recap:renderFinal", projectId),
  detectRecapHardware: () => ipcRenderer.invoke("recap:detectHardware"),
  generateStorytimeScript: (options) => ipcRenderer.invoke("storytime:generateScript", options),
  runSatisfyingStorytime: (options) => ipcRenderer.invoke("storytime:run", options),
  getStorytimeMatrixOptions: () => ipcRenderer.invoke("storytime:getMatrixOptions"),
  listVoices: (provider) => ipcRenderer.invoke("voice:list", provider),
  testVoice: (payload) => ipcRenderer.invoke("voice:test", payload),
  calibrateVoice: (payload) => ipcRenderer.invoke("voice:calibrate", payload),
  getVoiceProfile: (payload) => ipcRenderer.invoke("voice:getProfile", payload),
  openProjectFolder: (projectId) => ipcRenderer.invoke("project:openFolder", projectId),
  openOutput: (projectId) => ipcRenderer.invoke("project:openOutput", projectId),
  onProgress: (callback) => {
    ipcRenderer.removeAllListeners("pipeline:progress");
    ipcRenderer.on("pipeline:progress", (_event, payload) => callback(payload));
  },
  onVoiceProgress: (callback) => {
    ipcRenderer.removeAllListeners("voice:progress");
    ipcRenderer.on("voice:progress", (_event, payload) => callback(payload));
  },
  onSourceDownloadProgress: (callback) => {
    ipcRenderer.removeAllListeners("source:downloadProgress");
    ipcRenderer.on("source:downloadProgress", (_event, payload) => callback(payload));
  }
});
